### ISSUE TITLE
Invalid PIN does not re-prompt

### ISSUE THREAD

**Issue by r3cebarnett** [clemsonMakerspace/CATS#28] opened 2016-11-12 03:52 UTC
You have to take off the card and put it back on.

**Comment by ophilli** [comment] 2016-11-12 07:28
Fixed in commit 4af7ff2.

**Comment by ophilli** [comment] 2016-11-12 08:28
@mbgroom I am still able to reproduce this bug.

**Comment by gacosta1** [comment] 2017-01-11 16:29
Invalid PIN does re-prompt now, but I have to set a timer for maybe like 3 seconds for after it re-prompts because once the user is asked to re enter their PIN, it will sit on that option until they type a 4 digit PIN whether it's correct or not. hope that makes sense..

**Comment by gacosta1** [comment] 2017-01-11 16:32
Only option to solve that would be to use threading. If anyone else has ideas let me know. Cause as of now threading would allow us to listen for the user input while having a timer in the background.

**Comment by gacosta1** [comment] 2017-01-11 19:01
@gacosta1 Also threading would have to listen to the card reader as well as waiting for keypad input

**Comment by ophilli** [comment] 2017-01-11 20:29
@gacosta1 Sounds like we need to diagram the authentication flow.

**Comment by gacosta1** [comment] 2017-01-12 01:14
Most likely my friend.

**Comment by ophilli** [comment] 2017-01-12 01:27
@gacosta1 @gmross Can you put together an auth flow chart?

**Comment by gacosta1** [comment] 2017-01-12 20:08
As I sit in my Intro to Operating System class, I thought of a way that I could fix this little problem we have here. He's been talking about interrupts. Interrupts can be used to prevent issues or misuse in the operating system or memory or files. Sooo I think I can use an interrupt to set a time in the background while the user is trying to enter their PIN. Even if the card has been taken off of the card reader, the system will count for a certain time and if the user hasn't entered something it will lock them out.

**Comment by gacosta1** [comment] 2017-01-12 20:08
I'll try to code it when I get home.

**Comment by ophilli** [comment] 2017-01-13 16:46
@gacosta1 
![photo792993023636121735](https://cloud.githubusercontent.com/assets/964870/21960501/6cb32b94-dabc-11e6-8012-a8d37d7abb3e.jpg)

**Comment by r3cebarnett** [comment] 2017-01-14 04:16
Just made a pretty dope auth flow chart. Will commit in a few.
Edit: Committed under /software/

**Comment by gacosta1** [comment] 2017-01-15 05:46
It is finished. Rejoice.

**Comment by r3cebarnett** [comment] 2017-01-15 06:01
gj g i'm proud

**Comment by gacosta1** [comment] 2017-01-15 07:36
Found a bug while testing, but I fixed it. Officially finished. PR coming soon.

**Comment by ophilli** [comment] 2017-01-15 14:17
Can you write unit tests for this PR?

Owen Phillips

On Jan 15, 2017 2:36 AM, "Giandre Acosta" <notifications@github.com> wrote:

Found a bug while testing, but I fixed it. Official finished. PR coming
soon.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/clemsonMakerspace/CATS/issues/28#issuecomment-272679295>,
or mute the thread

**Comment by gacosta1** [comment] 2017-01-19 22:28
Will post PR tomorrow morning at 10AM sharp.

**Comment by ophilli** [comment] 2017-01-19 22:56
Lol wat

Owen Phillips

**Comment by gacosta1** [comment] 2017-01-19 22:57
Will create a PR tomorrow morning at 10AM sharp.

**Closed as completed** 2017-01-22 19:39 UTC
Labels: bug, software
